parameters:
#    equipo.example.class: Pachanga\EquipoBundle\Example

services:
#    equipo.example:
#        class: %equipo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
