# Ruta de la página de detalle de una anuncio
anuncio:
    pattern:  /{ciudad}/anuncios/{slug}
    defaults: { _controller: OfertaBundle:Default:anuncio }
responder:
    pattern:  /{ciudad}/anuncios/{slug}/responder
    defaults: { _controller: AnuncioBundle:Default:responder }
