<?php

namespace Pachanga\EquipoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
}
