<?php

namespace Pachanga\AnuncioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuncioRepository extends EntityRepository
{
    public function findAnunciosCiudad($city)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT a, ac, e, g, c
            FROM AnuncioBundle:Anuncio a JOIN a.actividad ac JOIN ac.equipo e JOIN e.grupo g JOIN g.ciudad c
            WHERE c.slug = :city
            ORDER BY a.fecha DESC
        ');
        $query->setMaxResults(10);
        $query->setParameter('city', $city);
        $query->useResultCache(true, 600);

        return $query->getResult();
    }
}
