<?php

namespace Pachanga\CodificadoresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeporteRepository extends EntityRepository
{
}
