parameters:
#    usuario.example.class: Pachanga\UsuarioBundle\Example

services:
    login_listener:
        class: Pachanga\UsuarioBundle\Listener\LoginListener
        scope: request
        arguments: [@router, @security.context]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
            - { name: kernel.event_listener, event: kernel.request }
